version: "3.3"
services:
  xkali:
    container_name: xkali
    user: gh0st
    build:
      context: .
    environment:
      DISPLAY: "${DISPLAY}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home/gh0st/:/home/gh0st/
    ports:
      - 127.0.0.1:8080:8080
      - 0.0.0.0:1337:1337
      - 0.0.0.0:9999:9999

