version: "3.3"
services:
  xkali:
    container_name: xkali
    user: "${USER}"
    build:
      context: .
      args:
        USER: "${USER}"
        SPACEVIM: "TRUE"
        RUSTUP: "TRUE"
    environment:
      DISPLAY: "${DISPLAY}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - "/home/${USER}/:/home/${USER}/"
      - /etc/hosts:/etc/hosts:ro
      - /opt/xkali-tools.d/:/opt/
    ports:
      - 127.0.0.1:8080:8080
      - 0.0.0.0:1337:1337
      - 0.0.0.0:9990-9999:9990-9999

